# Generated by Django 6.0.2 on 2026-03-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_customer_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customers',
            new_name='customer',
        ),
    ]
